import React from "react";
import ItineraryDayCard from "./ItineraryDayCard.jsx";

export default function ItineraryDraftPanel({
  itinerary,
  draftDays,
  tripTitle,
  draftVersion,
  budget,
  travelers,
  insights,
  onContinue,
  dispatchAgentMessage
}) {
  return (
    <div className="itinerary-draft-panel">
      <header className="draft-header">
        <div className="header-title">
          <h2>Live Itinerary</h2>
          <p>Real-time draft generated by your agent</p>
        </div>
        <div className="header-actions">
          <span className="draft-version-tag">
            <span className="dot"></span> {draftVersion}
          </span>
          <button className="btn-approve" onClick={onContinue}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><polyline points="20 6 9 17 4 12"/></svg>
            Approve Draft
          </button>
          <button className="btn-regenerate" onClick={() => dispatchAgentMessage("Regenerate this itinerary draft")}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2"><path d="M3 12a9 9 0 109-9 9.75 9.75 0 00-6.74 2.74L3 8"/><path d="M3 3v5h5"/></svg>
            Regenerate
          </button>
        </div>
      </header>

      <div className="metadata-map-row">
        <div className="metadata-strip">
          <div className="meta-item">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#9CA3AF" strokeWidth="2"><rect x="2" y="6" width="20" height="12" rx="2"/><path d="M12 12h.01"/><path d="M17 12h.01"/><path d="M7 12h.01"/></svg>
            <div className="meta-text">
              <span className="meta-label">Budget</span>
              <span className="meta-value">{budget || "$8,000 - $9,500"}</span>
            </div>
          </div>
          <div className="meta-item">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#9CA3AF" strokeWidth="2"><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>
            <div className="meta-text">
              <span className="meta-label">Pace</span>
              <span className="meta-value">Moderate</span>
            </div>
          </div>
          <div className="meta-item">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#9CA3AF" strokeWidth="2"><path d="M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2"/><circle cx="9" cy="7" r="4"/><path d="M23 21v-2a4 4 0 00-3-3.87"/><path d="M16 3.13a4 4 0 010 7.75"/></svg>
            <div className="meta-text">
              <span className="meta-label">Travelers</span>
              <span className="meta-value">{travelers || "2 Adults"}</span>
            </div>
          </div>
          <div className="meta-item">
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="#9CA3AF" strokeWidth="2"><path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"/></svg>
            <div className="meta-text">
              <span className="meta-label">Interests</span>
              <span className="meta-value">Scenic, Culture</span>
            </div>
          </div>
        </div>

        <div className="map-preview">
           <img src="https://images.unsplash.com/photo-1524661135-423995f22d0b?auto=format&fit=crop&w=400&q=80" alt="Map Route Preview" className="map-image" />
           <div className="map-overlay">
             <button className="view-map-btn">View Full Map ↗</button>
           </div>
        </div>
      </div>

      <div className="days-list">
        {(draftDays && draftDays.length > 0) ? (
          draftDays.map((day, index) => (
            <ItineraryDayCard key={day.dayNumber || index} day={day} dayIndex={index} />
          ))
        ) : (
          <>
            <ItineraryDayCard day={{ dayNumber: 1, title: "Arrive in Zermatt", locations: [] }} dayIndex={0} />
            <ItineraryDayCard day={{ dayNumber: 2, title: "Zermatt Explorer", locations: [] }} dayIndex={1} />
            <ItineraryDayCard day={{ dayNumber: 3, title: "Interlaken & Lucerne", locations: [] }} dayIndex={2} />
          </>
        )}
      </div>

      <style jsx>{`
        .itinerary-draft-panel {
          background: #FAFAFA;
          border-radius: 16px;
          border: 1px solid #E5E7EB;
          padding: 24px;
          display: flex;
          flex-direction: column;
          height: 100%;
          min-height: 800px;
          font-family: 'Inter', sans-serif;
          box-shadow: 0 4px 20px rgba(0, 0, 0, 0.02);
        }

        .draft-header {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          margin-bottom: 32px;
        }

        .header-title h2 {
          font-size: 18px;
          font-weight: 600;
          color: #111827;
          margin: 0 0 4px 0;
        }

        .header-title p {
          font-size: 13px;
          color: #6B7280;
          margin: 0;
        }

        .header-actions {
          display: flex;
          align-items: center;
          gap: 12px;
        }

        .draft-version-tag {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 6px 12px;
          background: white;
          border: 1px solid #E5E7EB;
          border-radius: 20px;
          font-size: 13px;
          font-weight: 500;
          color: #374151;
        }

        .dot {
          width: 6px;
          height: 6px;
          background: #D97706;
          border-radius: 50%;
        }

        .btn-approve, .btn-regenerate {
          display: flex;
          align-items: center;
          gap: 6px;
          padding: 8px 16px;
          border-radius: 8px;
          font-size: 14px;
          font-weight: 500;
          cursor: pointer;
          border: none;
        }

        .btn-approve {
          background: #B65D48;
          color: white;
        }

        .btn-regenerate {
          background: white;
          border: 1px solid #E5E7EB;
          color: #374151;
        }

        .metadata-map-row {
          display: flex;
          justify-content: space-between;
          align-items: flex-start;
          margin-bottom: 32px;
          position: relative;
        }

        .metadata-strip {
          display: flex;
          gap: 32px;
          background: white;
          padding: 16px 24px;
          border-radius: 12px;
          border: 1px solid #E5E7EB;
          flex: 1;
          max-width: 65%;
        }

        .meta-item {
          display: flex;
          align-items: center;
          gap: 12px;
        }

        .meta-text {
          display: flex;
          flex-direction: column;
        }

        .meta-label {
          font-size: 12px;
          color: #6B7280;
        }

        .meta-value {
          font-size: 14px;
          font-weight: 500;
          color: #111827;
        }

        .map-preview {
          position: absolute;
          right: 0;
          top: -20px;
          width: 300px;
          height: 120px;
          border-radius: 12px;
          overflow: hidden;
          box-shadow: 0 10px 25px rgba(0,0,0,0.1);
          border: 2px solid white;
        }

        .map-image {
          width: 100%;
          height: 100%;
          object-fit: cover;
        }

        .map-overlay {
          position: absolute;
          bottom: 8px;
          right: 8px;
        }

        .view-map-btn {
          background: rgba(255, 255, 255, 0.9);
          border: none;
          padding: 4px 10px;
          border-radius: 4px;
          font-size: 12px;
          font-weight: 500;
          cursor: pointer;
        }

        .days-list {
          display: flex;
          flex-direction: column;
        }

        .empty-state {
          padding: 40px;
          text-align: center;
          color: #6B7280;
          background: white;
          border-radius: 12px;
          border: 1px dashed #D1D5DB;
        }
      `}</style>
    </div>
  );
}
