"use client";

import { useState, useEffect } from "react";
import prototypeData from "./prototype-data";
import { usePrototypeState } from "./prototype-state";

const workspaceTabs = [
  { id: "trip", label: "Trip" },
  { id: "map", label: "Map" },
  { id: "agent", label: "Agent" },
  { id: "share", label: "Share" },
];

const tripBriefLabels = {
  destination: "Destination",
  travelWindow: "Travel window",
  travelers: "Travelers",
  pace: "Pace",
  budget: "Budget",
  priority: "Planning priorities",
};

const voyageSamples = [
  {
    id: "sample-1",
    title: "7 Days in Kyoto",
    subtitle: "Temples, Tea, and Timing",
    tags: ["Culture", "Slow Pace"],
  },
  {
    id: "sample-2",
    title: "Amalfi Drift",
    subtitle: "Coastal Routes & Hidden Coves",
    tags: ["Nature", "High Budget"],
  },
  {
    id: "sample-3",
    title: "Icelandic Ring",
    subtitle: "Geothermal Power & Glacial Pace",
    tags: ["Adventure", "Active"],
  },
];

function formatTripBriefValue(key, value) {
  if (key === "travelers") return `${value} travelers`;
  return value;
}

function LandingPage({ onStart }) {
  return (
    <div className="landing-container">
      {/* Hero Section */}
      <section className="landing-hero">
        <span className="frame-label">Voyage Intelligence</span>
        <h1 style={{ fontSize: 'clamp(4rem, 12vw, 7rem)', lineHeight: 0.9, marginBottom: '2rem' }}>
          The world, <br />
          <span style={{ color: 'var(--accent)', fontStyle: 'italic' }}>recharted.</span>
        </h1>
        <p className="lede" style={{ maxWidth: '600px' }}>
          A high-fidelity planning environment that turns the chaos of travel into an editorial journey. 
          Powered by spatial intelligence and your dedicated planning agent.
        </p>
        <div className="button-stack">
          <button className="button button-primary" onClick={onStart}>
            Start Your Voyage
          </button>
        </div>
        <div className="scroll-indicator">
          <span>↓</span>
        </div>
      </section>

      {/* Samples Section */}
      <section className="landing-section">
        <span className="frame-label">Planned by Voyage</span>
        <h2 style={{ fontSize: '3rem', marginBottom: '1rem' }}>Curated Expeditions</h2>
        <p className="lede">Sample itineraries generated by the Voyage Agent for refined travelers.</p>
        
        <div className="sample-grid">
          {voyageSamples.map((sample) => (
            <div key={sample.id} className="sample-card">
              <div className="sample-image-placeholder" />
              <div className="sample-content">
                <div style={{ display: 'flex', gap: '8px', marginBottom: '12px' }}>
                  {sample.tags.map(tag => (
                    <span key={tag} style={{ fontSize: '0.65rem', padding: '4px 8px', background: 'var(--accent-glow)', border: '1px solid var(--accent)', borderRadius: '4px', color: 'var(--accent)' }}>
                      {tag}
                    </span>
                  ))}
                </div>
                <h3 style={{ fontSize: '1.5rem', marginBottom: '4px' }}>{sample.title}</h3>
                <p style={{ fontSize: '0.9rem', color: 'var(--text-dim)' }}>{sample.subtitle}</p>
              </div>
            </div>
          ))}
        </div>
      </section>

      {/* Feature Section: The Atlas */}
      <section className="landing-section">
        <div className="frame-panel" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '40px', alignItems: 'center' }}>
          <div>
            <span className="frame-label">01. The Atlas</span>
            <h2 style={{ fontSize: '2.5rem', marginBottom: '1.5rem' }}>Itinerary-first thinking.</h2>
            <p className="lede">
              The itinerary is the operating system of your trip. We prioritize daily rhythm, 
              clustering stops logically and leaving room for the unplanned.
            </p>
          </div>
          <div className="day-card" style={{ transform: 'rotate(2deg)', opacity: 0.8 }}>
            <span className="frame-label">Prototype Wireframe</span>
            <div style={{ height: '200px', background: 'var(--bg-glass)', borderRadius: '8px', border: '1px dashed var(--border-bright)' }}></div>
          </div>
        </div>
      </section>

      {/* Feature Section: The Agent */}
      <section className="landing-section">
        <div className="frame-panel" style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '40px', alignItems: 'center' }}>
          <div className="day-card" style={{ transform: 'rotate(-2deg)', opacity: 0.8, order: 2 }}>
            <span className="frame-label">Agent Interface</span>
            <div style={{ height: '200px', background: 'var(--bg-glass)', borderRadius: '8px', border: '1px dashed var(--border-bright)' }}></div>
          </div>
          <div style={{ order: 1 }}>
            <span className="frame-label">02. The Copilot</span>
            <h2 style={{ fontSize: '2.5rem', marginBottom: '1.5rem' }}>Intelligence on call.</h2>
            <p className="lede">
              The Voyage Agent isn't just a chatbot. It's a spatial engine that understands 
              distance, tempo, and your personal priorities.
            </p>
          </div>
        </div>
      </section>

      {/* Final CTA */}
      <section className="landing-section" style={{ textAlign: 'center', alignItems: 'center' }}>
        <h2 style={{ fontSize: '3.5rem', marginBottom: '2rem' }}>Ready to depart?</h2>
        <button className="button button-primary" onClick={onStart} style={{ padding: '20px 48px', fontSize: '1.2rem' }}>
          Begin Planning
        </button>
      </section>

      <footer style={{ padding: '60px 0', borderTop: '1px solid var(--border-glass)', marginTop: '80px', color: 'var(--text-dim)', fontSize: '0.9rem' }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
          <span>© 2026 Voyage Intelligence. All rights reserved.</span>
          <div style={{ display: 'flex', gap: '24px' }}>
            <span>Privacy</span>
            <span>Terms</span>
            <span>Atlas API</span>
          </div>
        </div>
      </footer>
    </div>
  );
}

function EntryScreen({ email, onEmailChange, onGuest }) {
  return (
    <section className="screen-frame">
      <div className="frame-panel">
        <span className="frame-label">Identity</span>
        <h2>Continue your journey</h2>
        <p className="lede">Sign in to sync your itineraries across all your devices.</p>

        <div className="input-row">
          <span>Email address</span>
          <input
            type="email"
            value={email}
            onChange={(e) => onEmailChange(e.target.value)}
            placeholder="voyager@example.com"
          />
        </div>

        <div style={{ marginBottom: '2rem', fontSize: '0.8rem', color: 'var(--text-dim)' }}>
          Social authentication (Google, Apple) will be available in the release version.
        </div>

        <button className="button button-primary" onClick={onGuest} style={{ width: '100%' }}>
          Continue as Guest
        </button>
      </div>
    </section>
  );
}

function TripBriefScreen({ onContinue, tripBrief }) {
  return (
    <section className="screen-frame">
      <div className="frame-panel">
        <span className="frame-label">Project Brief</span>
        <h2>Defining the scope</h2>
        <p className="lede">The foundation of every great Voyage starts with a clear brief.</p>

        <div className="field-grid">
          {Object.entries(tripBrief).map(([key, value]) => (
            <div key={key} className="input-row">
              <span>{tripBriefLabels[key] ?? key}</span>
              <strong>{formatTripBriefValue(key, value)}</strong>
            </div>
          ))}
        </div>

        <button className="button button-primary" onClick={onContinue} style={{ width: '100%' }}>
          Initialize Voyage Agent
        </button>
      </div>
    </section>
  );
}

function AgentKickoffScreen({ onOpenWorkspace, tripBrief }) {
  return (
    <section className="screen-frame">
      <div className="frame-panel" style={{ display: 'grid', gridTemplateColumns: '1fr 300px', gap: '40px' }}>
        <div>
          <span className="frame-label">Agent Sync</span>
          <h2>Your copilot is ready.</h2>
          <p className="lede">
            The Voyage Agent has processed your brief for {tripBrief.destination}. 
            We've mapped out potential clusters and optimized for your {tripBrief.pace} pace.
          </p>

          <button className="button button-primary" onClick={onOpenWorkspace} style={{ marginTop: '2rem' }}>
            Enter Workspace
          </button>
        </div>

        <div style={{ background: 'rgba(255,255,255,0.02)', padding: '24px', borderRadius: 'var(--radius-md)', border: '1px solid var(--border-glass)' }}>
          <div className="detail-block">
            <p>Processing...</p>
            <ul>
              <li>Destination: {tripBrief.destination}</li>
              <li>Tempo: {tripBrief.pace}</li>
              <li>Priority: {tripBrief.priority}</li>
            </ul>
          </div>
          <div className="detail-block" style={{ marginBottom: 0 }}>
            <p>Module Status</p>
            <ul style={{ color: 'var(--accent-secondary)' }}>
              <li>Itinerary Engine: OK</li>
              <li>Map Overlay: Ready</li>
              <li>Agent Memory: Initialized</li>
            </ul>
          </div>
        </div>
      </div>
    </section>
  );
}

function WorkspaceScreen({
  activeWorkspaceTab,
  agentMessages,
  days,
  onReviewTrip,
  onSelectDay,
  onSelectPlace,
  onTabChange,
  selectedDay,
  selectedDayId,
  selectedPlace,
  tripBrief,
}) {
  return (
    <section className="screen-frame screen-editor">
      {/* Navigation Sidebar */}
      <aside className="frame-panel frame-panel-nav" style={{ padding: '0', background: 'transparent', border: 'none', boxShadow: 'none' }}>
        <div className="frame-panel" style={{ padding: '24px', marginBottom: '24px' }}>
          <span className="frame-label">Voyage</span>
          <h3 style={{ fontSize: '1.5rem' }}>{tripBrief.destination}</h3>
          <p style={{ fontSize: '0.8rem', color: 'var(--text-dim)', marginTop: '8px' }}>
            {tripBrief.travelWindow}
          </p>
        </div>

        <div style={{ display: 'grid', gap: '12px', marginBottom: '24px' }}>
          {workspaceTabs.map((tab) => (
            <button
              key={tab.id}
              className={`topbar-chip ${activeWorkspaceTab === tab.id ? 'active' : ''}`}
              onClick={() => onTabChange(tab.id)}
            >
              {tab.label}
            </button>
          ))}
        </div>

        <div className="frame-panel" style={{ padding: '24px' }}>
          <span className="frame-label">Timeline</span>
          <div style={{ marginTop: '16px' }}>
            {days.map((day) => (
              <button
                key={day.id}
                className={`day-pill ${selectedDayId === day.id ? 'active' : ''}`}
                style={{ width: '100%', textAlign: 'left' }}
                onClick={() => onSelectDay(day.id)}
              >
                <span>{day.label}</span>
                <strong style={{ fontSize: '0.9rem' }}>{day.title}</strong>
              </button>
            ))}
          </div>
        </div>
      </aside>

      {/* Main Content Area */}
      <main className="frame-panel frame-panel-board">
        {activeWorkspaceTab === "trip" && (
          <div className="day-split">
            <div>
              <span className="frame-label">Itinerary Editor</span>
              <h3>{selectedDay?.title ?? "Planning Overview"}</h3>
              <p className="lede" style={{ marginBottom: '1rem' }}>
                Refine the rhythm of your days. Drag and drop stops to reorder.
              </p>
            </div>

            <div style={{ display: 'grid', gap: '20px' }}>
              {days.map((day) => (
                <article key={day.id} className={`day-card ${selectedDayId === day.id ? 'selected' : ''}`} style={{ borderLeft: selectedDayId === day.id ? '4px solid var(--accent)' : '' }}>
                  <div className="day-card-head">
                    <div>
                      <span className="frame-label">{day.label}</span>
                      <strong style={{ fontSize: '1.3rem' }}>{day.title}</strong>
                    </div>
                    <button className="button button-secondary" style={{ padding: '8px 16px', fontSize: '0.8rem' }} onClick={() => onSelectDay(day.id)}>
                      {selectedDayId === day.id ? 'Active' : 'Focus'}
                    </button>
                  </div>
                  
                  <div style={{ display: 'grid', gap: '8px' }}>
                    {day.stops.map((stop) => (
                      <div key={stop} className="activity-chip">
                        <span className="chip-drag"></span>
                        <span style={{ fontSize: '0.95rem' }}>{stop}</span>
                      </div>
                    ))}
                  </div>
                </article>
              ))}
            </div>
          </div>
        )}

        {activeWorkspaceTab === "map" && (
          <div className="day-split">
            <div>
              <span className="frame-label">Spatial Planning</span>
              <h3>Map Discovery</h3>
              <p className="lede">Anchors and potential stops clustered for efficiency.</p>
            </div>

            <div className="day-card" style={{ background: 'var(--accent-glow)', borderColor: 'var(--accent)' }}>
              <span className="frame-label" style={{ color: 'var(--text-main)' }}>Focused Anchor</span>
              <h4 style={{ fontSize: '1.2rem', marginBottom: '8px' }}>{selectedPlace?.name ?? "Select a point on the map"}</h4>
              <p style={{ color: 'var(--text-main)', opacity: 0.8 }}>{selectedPlace?.note}</p>
            </div>

            <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: '16px' }}>
              {prototypeData.mapPlaces.map((place) => (
                <button
                  key={place.id}
                  className={`day-card ${selectedPlace?.id === place.id ? 'selected' : ''}`}
                  style={{ textAlign: 'left', cursor: 'pointer' }}
                  onClick={() => onSelectPlace(place.id)}
                >
                  <span style={{ fontSize: '0.7rem', color: 'var(--accent)' }}>{place.district}</span>
                  <strong style={{ display: 'block', fontSize: '1rem', marginTop: '4px' }}>{place.name}</strong>
                </button>
              ))}
            </div>
          </div>
        )}

        {activeWorkspaceTab === "agent" && (
          <div className="day-split">
            <div>
              <span className="frame-label">AI Intelligence</span>
              <h3>Voyage Agent</h3>
              <p className="lede">Conversational refinement for your itinerary.</p>
            </div>

            <div style={{ display: 'grid', gap: '16px' }}>
              {agentMessages.map((msg) => (
                <div key={msg.id} className="share-row" style={{ borderLeft: msg.role === 'assistant' ? '2px solid var(--accent)' : '2px solid var(--text-dim)' }}>
                  <strong>{msg.role === 'assistant' ? 'Voyage Agent' : 'You'}</strong>
                  <p>{msg.text}</p>
                </div>
              ))}
            </div>
            
            <div className="input-row" style={{ marginTop: '20px' }}>
              <input type="text" placeholder="Ask about reservations, clusters, or pace..." style={{ background: 'var(--bg-glass)', border: '1px solid var(--border-glass)', borderRadius: 'var(--radius-md)', padding: '16px', color: '#fff', width: '100%' }} />
            </div>
          </div>
        )}

        {activeWorkspaceTab === "share" && (
          <div className="day-split">
            <div>
              <span className="frame-label">Deployment</span>
              <h3>Trip Finalization</h3>
              <p className="lede">Exporting your plans to high-fidelity formats.</p>
            </div>
            <div className="day-card">
              <p>Ready to deploy your itinerary for {tripBrief.destination}.</p>
              <button className="button button-primary" style={{ marginTop: '16px' }} onClick={onReviewTrip}>
                Review & Export
              </button>
            </div>
          </div>
        )}
      </main>

      {/* Detail Panel */}
      <aside className="frame-panel frame-panel-detail">
        <span className="frame-label">Quick Insights</span>
        
        <div className="detail-block">
          <p>Context</p>
          <strong style={{ fontSize: '1rem', marginBottom: '8px', display: 'block' }}>{tripBrief.destination}</strong>
          <ul style={{ fontSize: '0.85rem' }}>
            <li>{tripBrief.travelers} Travelers</li>
            <li>{tripBrief.pace}</li>
            <li>Budget: {tripBrief.budget}</li>
          </ul>
        </div>

        {selectedDay && (
          <div className="detail-block">
            <p>Active Day: {selectedDay.label}</p>
            <strong style={{ fontSize: '1rem', marginBottom: '8px', display: 'block' }}>{selectedDay.title}</strong>
            <ul>
              {selectedDay.stops.map(stop => <li key={stop}>{stop}</li>)}
            </ul>
          </div>
        )}

        <div style={{ marginTop: 'auto' }}>
          <button className="button button-primary" style={{ width: '100%' }} onClick={onReviewTrip}>
            Final Review
          </button>
        </div>
      </aside>
    </section>
  );
}

function ReviewScreen({ days, onBackToWorkspace, onShare, tripBrief }) {
  return (
    <section className="screen-frame">
      <div className="frame-panel">
        <span className="frame-label">Review</span>
        <h2>The Grand Tour</h2>
        <p className="lede">Final check of your itinerary for {tripBrief.destination}.</p>

        <div style={{ display: 'grid', gap: '12px', marginBottom: '32px' }}>
          {days.map((day) => (
            <div key={day.id} className="day-card" style={{ padding: '16px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between' }}>
                <strong>{day.label}: {day.title}</strong>
                <span style={{ fontSize: '0.8rem', color: 'var(--text-dim)' }}>{day.stops.length} stops</span>
              </div>
            </div>
          ))}
        </div>

        <div className="button-stack">
          <button className="button button-secondary" onClick={onBackToWorkspace}>
            Adjust Plans
          </button>
          <button className="button button-primary" onClick={onShare}>
            Confirm Voyage
          </button>
        </div>
      </div>
    </section>
  );
}

function ShareScreen({ onBackToWorkspace }) {
  return (
    <section className="screen-frame">
      <div className="frame-panel">
        <span className="frame-label">Transmission</span>
        <h2>Share your Voyage</h2>
        <p className="lede">Project your itinerary to collaborators and devices.</p>

        <div className="share-list">
          <div className="share-row">
            <strong>Direct Link</strong>
            <span>Generate a secure URL for mobile viewing.</span>
          </div>
          <div className="share-row">
            <strong>Collaborator Access</strong>
            <span>Invite others to co-edit the itinerary.</span>
          </div>
          <div className="share-row">
            <strong>PDF Export</strong>
            <span>Create a high-fidelity print snapshot.</span>
          </div>
        </div>

        <button className="button button-primary" onClick={onBackToWorkspace} style={{ marginTop: '32px', width: '100%' }}>
          Return to Workspace
        </button>
      </div>
    </section>
  );
}

export default function HomePage() {
  const {
    activeScreen,
    setActiveScreen,
    activeWorkspaceTab,
    setActiveWorkspaceTab,
    tripBrief,
    days,
    selectedDayId,
    setSelectedDayId,
    selectedPlaceId,
    setSelectedPlaceId,
    agentMessages,
  } = usePrototypeState();

  const currentScreen = activeScreen === "landing" ? "welcome" : activeScreen;
  const currentWorkspaceTab = activeWorkspaceTab === 'overview' || activeWorkspaceTab === 'itinerary' ? 'trip' : activeWorkspaceTab;
  
  const selectedDay = days.find((day) => day.id === selectedDayId) || days[0];
  const selectedPlace = prototypeData.mapPlaces.find((place) => place.id === selectedPlaceId) || prototypeData.mapPlaces[0];
  
  const [email, setEmail] = useState("");

  return (
    <main className="system-shell">
      <div className="system-grain" aria-hidden="true" />

      <section className="wireframe-section">
        {currentScreen === "welcome" && (
          <LandingPage
            onStart={() => setActiveScreen("entry")}
          />
        )}

        {currentScreen === "entry" && (
          <EntryScreen
            email={email}
            onEmailChange={setEmail}
            onGuest={() => setActiveScreen("trip-brief")}
          />
        )}

        {currentScreen === "trip-brief" && (
          <TripBriefScreen onContinue={() => setActiveScreen("agent-kickoff")} tripBrief={tripBrief} />
        )}

        {currentScreen === "agent-kickoff" && (
          <AgentKickoffScreen
            onOpenWorkspace={() => setActiveScreen("workspace")}
            tripBrief={tripBrief}
          />
        )}

        {currentScreen === "workspace" && (
          <WorkspaceScreen
            activeWorkspaceTab={currentWorkspaceTab}
            agentMessages={agentMessages}
            days={days}
            onReviewTrip={() => setActiveScreen("review")}
            onSelectDay={setSelectedDayId}
            onSelectPlace={setSelectedPlaceId}
            onTabChange={(tab) => {
              setActiveWorkspaceTab(tab);
              if (tab === 'map' && !selectedPlaceId) setSelectedPlaceId(prototypeData.mapPlaces[0].id);
            }}
            selectedDay={selectedDay}
            selectedDayId={selectedDayId}
            selectedPlace={selectedPlace}
            tripBrief={tripBrief}
          />
        )}

        {currentScreen === "review" && (
          <ReviewScreen
            days={days}
            onBackToWorkspace={() => setActiveScreen("workspace")}
            onShare={() => setActiveScreen("share")}
            tripBrief={tripBrief}
          />
        )}

        {currentScreen === "share" && (
          <ShareScreen onBackToWorkspace={() => setActiveScreen("workspace")} />
        )}
      </section>
    </main>
  );
}
